wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709754368.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.18
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.1
optimizer:
  desc: null
  value: adam
